name: Deploy
on:
  push:
    branches:
      - main  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run lint
      - name: Test code
        run: npm run test
  build: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist-files
          path: dist
          # path: |
          #   dist
          #   package.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build artifacs
        uses: actions/download-artifacts@v3   
        with: 
          name: dist-files
      - name: Output content
        run: ls
      - name: Deploy
        run: echo "Deploying to server"