name: Deploy
on:
  push:
    branches:
      - main  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run lint
      - name: Test code
        run: npm run test
  build: 
    runs-on: ubuntu-latest
    needs: test
    output:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish JS file
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';' 
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist-files
          path: dist
          # path: |
          #   dist
          #   package.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build artifacs
        uses: actions/download-artifact@v3   
        with: 
          name: dist-files
      - name: Output content
        run: ls
      - name: Output file name
        run: echo ${{ needs.build.outputs.script-file }}
      - name: Deploy
        run: echo "Deploying to server"